module.exports.descriptions = [
    "This family - friendly campground is situated on a beautiful lake, surrounded by lush trees and rolling hills.The campground has plenty of sites for pitching tents or parking RVs, and amenities like fire pits, picnic tables, and a communal kitchen.",
    "This off - the - beaten - path campground is perfect for those looking for a peaceful getaway.With miles of untouched nature and an array of wildlife, this campground is sure to provide an unforgettable experience.The sites are perfect for tents and small RVs, and offer amenities like fire pits and picnic tables.",
    "This rustic campground is the perfect place to reconnect with nature.Set in the heart of a dense forest, the campground has sites for tents and small RVs, as well as amenities like fire pits, picnic tables, and a communal kitchen.",
    "This beachfront campground is the perfect spot for a summer getaway.The campground is located directly on the beach, and offers plenty of sites for tents and RVs.Amenities like fire pits, picnic tables, and grills make it a great spot for beachside barbecues.",
    "A rustic campground surrounded by tall pine trees, with a nearby lake for fishing, swimming and kayaking.",
    "A family - friendly campground with a playground, picnic area, fire pits, and plenty of space for tents and RVs.",
    "A secluded campground with scenic views of the nearby mountain range, and a winding river running nearby.",
    "A nature - filled campground with a nearby lake and plenty of trails to explore.",
    "A spacious campground with a variety of amenities, including a swimming pool, mini golf course, and game room.",
    "A peaceful campground surrounded by lush green woodland, with plenty of space for tents and RVs.",
    "An open campground with plenty of space for outdoor activities, such as volleyball, horseshoes and more.",
    "A beachfront campground with beach access, fire pits, and plenty of space for tents and RVs.",
    "A spacious campground with a wide variety of activities, including a basketball court, fishing dock, and more.",
    "A luxury campground with a variety of amenities, including a swimming pool, spa, and restaurant.",
    "Nestled in the foothills of the Appalachian Mountains, our picturesque campground offers a tranquil retreat from the hustle and bustle of daily life.With a variety of camping sites to choose from, you'll find plenty of opportunities to relax and explore the area's natural beauty.Enjoy a dip in the crystal - clear lake, pitch a tent in the shaded woods, or take a leisurely stroll along the trails.Regardless of what you choose, you’ll be sure to make memories that will last a lifetime.",
    "Our family - friendly campground is the perfect getaway for those looking for a peaceful escape.Nestled in the rolling hills of the countryside, it offers plenty of amenities to make your stay enjoyable.Pitch your tent or park your RV in one of the lush grassy fields, and spend your days fishing in the nearby lake, exploring the surrounding forest, or soaking up some sun on the sandy beach.At night, sit around the campfire and roast marshmallows under the stars.",
    "Nestled in the rolling hills of the Appalachian Mountains, our campground offers a peaceful, picturesque getaway. Enjoy hiking, fishing, and swimming in the lake, plus plenty of other outdoor activities.Onsite amenities include a camp store, a playground, and a recreation center with a game room, mini golf, and more.Our campground is the perfect place to reconnect with nature and make memories with family and friends.",
    "Located on the edge of a lush forest, our campground provides a peaceful escape from the hustle and bustle of everyday life. Whether you're looking to relax in a hammock or explore the nearby trails, our campground offers something for everyone.Amenities include a heated pool, a playground, a fire pit, and a camp store.Come stay with us and experience a tranquil camping adventure.",
    "Our campground provides a peaceful, family - friendly atmosphere for your camping holiday.Spend your days fishing in the nearby lake, or explore the stunning natural surroundings.Onsite amenities include a camp store, a playground, and a recreation center with a game room, mini golf, and more.Enjoy a fun and relaxing camping experience at our beautiful campground."
];

module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
];

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
];

module.exports.firstNames = [
    'Sophia',
    'Noah',
    'Emma',
    'Liam',
    'Olivia',
    'Jacob',
    'Ava',
    'Mason',
    'Isabella',
    'William',
    'Mia',
    'Ethan',
    'Charlotte',
    'Michael',
    'Amelia',
    'John',
    'Mary',
    'George',
    'James',
    'Ann',
    'Paul',
    'Michael',
    'Margaret',
    'William',
    'Emily',
    'Richard',
    'Susan',
    'Charles',
    'Jessica',
    'Joseph',
    'Linda',
    'David',
    'Karen',
    'Thomas',
    'Barbara',
    'Robert',
    'Betty',
    'Mark',
    'Helen',
    'Brian',
    'Sandra',
    'Jeffrey',
    'Donna',
    'Donald',
    'Ashley',
    'Gary',
    'Kimberly',
    'Steven',
    'Stephanie',
    'Scott',
    'Amanda',
    'Larry',
    'Patricia',
    'Andrew',
    'Jennifer',
    'Matthew',
    'Elizabeth',
    'Daniel',
    'Laura',
    'Anthony',
    'Rachel',
    'Kevin',
    'Deborah',
    'Edward',
    'Rebecca',
    'Timothy',
    'Sharon',
    'Jason',
    'Michelle',
    'Christopher',
    'Maria',
    'Jerry',
    'Diana',
];

module.exports.lastNames = [
    'Smith',
    'Johnson',
    'Williams',
    'Jones',
    'Brown',
    'Davis',
    'Miller',
    'Wilson',
    'Moore',
    'Taylor',
    'Anderson',
    'Thomas',
    'Jackson',
    'White',
    'Harris'
];

module.exports.revs = [
    'Great campground with plenty of space, great views and clean bathrooms!',
    'So much to do and see here! Highly recommend!',
    'Absolutely gorgeous and peaceful. Perfect for a weekend getaway.',
    'Loved the amenities and the friendly staff. Highly recommend.',
    'Amazing spot to camp! Spectacular views and great facilities.',
    'Great campground with lots of activities and friendly staff.',
    'Wonderful spot for a camping trip. Clean bathrooms, plenty of space and great views.',
    'Amazing campground! Lots of activities and friendly staff.',
    'Fantastic campground! Beautiful scenery, plenty of space and great facilities.',
    'Absolutely stunning campground! Great views and lots of activities.',
    'Fantastic campground with plenty of space, great facilities and friendly staff.',
    'Loved the campsite! Friendly staff, plenty of activities and great views.',
    'Great place to camp! Clean bathrooms, plenty of space and nice views.',
    'Amazing campground! Great views, plenty of activities and friendly staff.',
    'We had a great time at this campground! The sites were spacious, clean, and had plenty of shade.The staff was friendly and accommodating, and the amenities were top - notch.Highly recommend!',
    'We had an amazing stay at this campground! The facilities were well - maintained and the staff was incredibly helpful and welcoming.We would definitely recommend it to anyone looking for a peaceful weekend away.',
    'This campground was an excellent choice for our family vacation.The sites were clean and there were plenty of activities to keep us entertained.We highly recommend this campground to anyone looking for a great time.',
    'We had a fantastic time camping at this campground.The sites were roomy and well - kept.The staff was friendly and accommodating.We would definitely come back again!',
    'We had a wonderful stay at this campground.The sites were comfortable and the facilities were well - maintained.The staff was helpful and knowledgeable, and the activities were fun.Highly recommend this campground!'
];